# Generated by Django 4.0.5 on 2023-09-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_editprofile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
    ]
